# Generated by Django 5.1.5 on 2026-06-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('department_name', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('closed', 'Closed'), ('archived', 'Archived')], default='running', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
