# Generated by Django 5.2.15 on 2026-06-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
