# Generated by Django 5.2.15 on 2026-06-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_quiz_quizattempt_quizquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=64)),
                ('course_title', models.CharField(blank=True, max_length=255)),
                ('course_code', models.CharField(blank=True, max_length=64)),
                ('credits', models.PositiveIntegerField(default=3)),
                ('academic_year', models.CharField(max_length=32)),
                ('semester', models.CharField(max_length=32)),
                ('assignment1', models.PositiveIntegerField(default=0)),
                ('assignment2', models.PositiveIntegerField(default=0)),
                ('midterm', models.PositiveIntegerField(default=0)),
                ('participation', models.PositiveIntegerField(default=0)),
                ('final_exam', models.PositiveIntegerField(default=0)),
                ('marks', models.PositiveIntegerField(default=0)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('grade_point', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-academic_year', '-semester', 'course_code'],
            },
        ),
    ]
