# Generated by Django 5.2.15 on 2026-06-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_message_messagedraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='college',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='id_card_valid_thru',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='programme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='year',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
