# Generated by Django 5.1.5 on 2026-06-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='assignment',
            name='lecturer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='lecturer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='author_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
