# Generated by Django 5.1.5 on 2026-06-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_course_courseunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('entity', models.CharField(blank=True, default='', max_length=64)),
                ('entity_id', models.CharField(blank=True, default='', max_length=255)),
                ('entity_name', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(blank=True, default='', max_length=255)),
                ('user_name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('year_level', models.IntegerField(default=1)),
                ('semester', models.IntegerField(default=1)),
                ('academic_year', models.CharField(max_length=32)),
                ('amount', models.FloatField(default=0)),
                ('currency', models.CharField(blank=True, default='UGX', max_length=16)),
                ('college', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['academic_year', 'year_level', 'semester'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer')], max_length=20)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('college', models.CharField(blank=True, default='', max_length=255)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=1024)),
                ('is_registered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_number', models.CharField(blank=True, default='', max_length=64)),
                ('registration_number', models.CharField(blank=True, default='', max_length=64)),
                ('program', models.CharField(blank=True, default='', max_length=255)),
                ('year_of_study', models.IntegerField(default=1)),
                ('status', models.CharField(blank=True, default='Active', max_length=32)),
                ('admission_date', models.CharField(blank=True, default='', max_length=32)),
                ('lecturer_number', models.CharField(blank=True, default='', max_length=64)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('address', models.TextField(blank=True, default='')),
                ('bio', models.TextField(blank=True, default='')),
                ('specialization', models.CharField(blank=True, default='', max_length=255)),
                ('employment_date', models.CharField(blank=True, default='', max_length=32)),
                ('assigned_course_units', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('employee_id', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('college', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer_id', models.CharField(max_length=255)),
                ('lecturer_name', models.CharField(blank=True, default='', max_length=255)),
                ('lecturer_email', models.CharField(blank=True, default='', max_length=255)),
                ('course_unit_id', models.CharField(max_length=255)),
                ('course_unit_code', models.CharField(blank=True, default='', max_length=64)),
                ('course_unit_name', models.CharField(blank=True, default='', max_length=255)),
                ('course_id', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_by', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='active', max_length=32)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=255)),
                ('course_id', models.CharField(blank=True, default='', max_length=255)),
                ('academic_year', models.CharField(max_length=32)),
                ('semester', models.CharField(max_length=32)),
                ('total', models.FloatField(default=0)),
                ('grade', models.CharField(blank=True, default='', max_length=10)),
                ('gp', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['student_id', 'academic_year', 'semester'],
            },
        ),
    ]
