# Generated by Django 5.1.5 on 2026-06-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_classroom_enrollment_livesession_submission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=64)),
                ('day_of_week', models.IntegerField()),
                ('start_time', models.CharField(max_length=16)),
                ('end_time', models.CharField(max_length=16)),
                ('room', models.CharField(blank=True, default='', max_length=64)),
                ('building', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0)),
                ('paid_amount', models.FloatField(default=0)),
                ('due_date', models.DateTimeField()),
                ('semester', models.CharField(blank=True, default='', max_length=32)),
                ('academic_year', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
    ]
