# Generated by Django 5.1.5 on 2026-06-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_submission_feedback_submission_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
