from django.urls import path

from .views import (
    HealthView,
    AuthLoginView,
    AuthLogoutView,
    AuthMeView,
    AuthSignupView,
    AuthResetPasswordView,
    SendSignupOtpView,
    ValidateStudentRecordView,
    VerifySignupOtpView,
    ProgramListView,
    AcademicCalendarView,
    AnnouncementListView,
    AnnouncementDetailView,
    AssignmentListView,
    QuizListView,
    QuizDetailView,
    QuizSubmitView,
    StudentResultsView,
    StudentExamResultsView,
    StudentQuizResultsView,
    StudentListView,
    LecturerSummaryView,
    MessageListView,
    MessageDetailView,
    MessageSendView,
    MessageActionView,
    DraftListView,
    DraftSaveView,
    DraftDeleteView,
    StudentProfileView,
    StudentSettingsView,
    CourseListView,
    CourseDetailView,
    CourseUnitListView,
    CourseUnitDetailView,
    ProfileListView,
    ProfileDetailView,
    RegistrarDetailView,
    FeeAssignmentListView,
    FeeAssignmentDetailView,
    AcademicCalendarEventListView,
    AcademicCalendarEventDetailView,
    StudentGradeListView,
    ActivityListView,
    SignUpListView,
    StudentDashboardView,
    LiveSessionListView,
    ClassroomListView,
    ClassroomEnrollView,
    ClassroomJoinView,
    EnrollmentListView,
    ScheduleListView,
    StudentFeeListView,
)

urlpatterns = [
    path("health/", HealthView.as_view()),
    path("auth/login/", AuthLoginView.as_view()),
    path("auth/logout/", AuthLogoutView.as_view()),
    path("auth/me/", AuthMeView.as_view()),
    path("auth/signup/", AuthSignupView.as_view()),
    path("auth/reset-password/", AuthResetPasswordView.as_view()),
    path("auth/validate-student-record/", ValidateStudentRecordView.as_view()),
    path("auth/send-signup-otp/", SendSignupOtpView.as_view()),
    path("auth/verify-signup-otp/", VerifySignupOtpView.as_view()),
    path("programs/", ProgramListView.as_view()),
    path("academic-calendar/", AcademicCalendarView.as_view()),
    path("announcements/", AnnouncementListView.as_view()),
    path("announcements/<int:announcement_id>/", AnnouncementDetailView.as_view()),
    path("assignments/", AssignmentListView.as_view()),
    path("quizzes/", QuizListView.as_view()),
    path("quizzes/<int:quiz_id>/", QuizDetailView.as_view()),
    path("quizzes/submit/", QuizSubmitView.as_view()),
    path("students/<str:student_id>/results/", StudentResultsView.as_view()),
    path("students/<str:student_id>/results/exams/", StudentExamResultsView.as_view()),
    path("students/<str:student_id>/results/quizzes/", StudentQuizResultsView.as_view()),
    path("students/<str:student_id>/profile/", StudentProfileView.as_view()),
    path("students/<str:user_id>/settings/", StudentSettingsView.as_view()),
    path("students/", StudentListView.as_view()),
    path("lecturer/summary/", LecturerSummaryView.as_view()),
    path("messages/<str:user_id>/", MessageListView.as_view()),
    path("messages/<int:message_id>/detail/", MessageDetailView.as_view()),
    path("messages/send/", MessageSendView.as_view()),
    path("messages/<int:message_id>/action/", MessageActionView.as_view()),
    path("drafts/<str:user_id>/", DraftListView.as_view()),
    path("drafts/save/", DraftSaveView.as_view()),
    path("drafts/<int:draft_id>/delete/", DraftDeleteView.as_view()),
    path("courses/", CourseListView.as_view()),
    path("courses/<int:course_id>/", CourseDetailView.as_view()),
    path("course-units/", CourseUnitListView.as_view()),
    path("course-units/<int:unit_id>/", CourseUnitDetailView.as_view()),
    path("profiles/", ProfileListView.as_view()),
    path("profiles/<int:profile_id>/", ProfileDetailView.as_view()),
    path("registrars/<str:user_id>/", RegistrarDetailView.as_view()),
    path("fee-assignments/", FeeAssignmentListView.as_view()),
    path("fee-assignments/<int:fee_id>/", FeeAssignmentDetailView.as_view()),
    path("academic-events/", AcademicCalendarEventListView.as_view()),
    path("academic-events/<int:event_id>/", AcademicCalendarEventDetailView.as_view()),
    path("student-grades/", StudentGradeListView.as_view()),
    path("student-grades/<int:grade_id>/", StudentGradeListView.as_view()),
    path("activities/", ActivityListView.as_view()),
    path("sign-ups/", SignUpListView.as_view()),
    path("students/<str:student_id>/dashboard/", StudentDashboardView.as_view()),
    path("live-sessions/", LiveSessionListView.as_view()),
    path("classrooms/", ClassroomListView.as_view()),
    path("classrooms/enroll/", ClassroomEnrollView.as_view()),
    path("classrooms/join/", ClassroomJoinView.as_view()),
    path("enrollments/", EnrollmentListView.as_view()),
    path("schedules/", ScheduleListView.as_view()),
    path("student-fees/", StudentFeeListView.as_view()),
]
