from django.urls import path

from .views import (
    HealthView,
    SendSignupOtpView,
    ValidateStudentRecordView,
    VerifySignupOtpView,
    ProgramListView,
    AcademicCalendarView,
    AnnouncementListView,
    AssignmentListView,
    QuizListView,
    QuizDetailView,
    QuizSubmitView,
    StudentResultsView,
    StudentExamResultsView,
    StudentQuizResultsView,
    MessageListView,
    MessageDetailView,
    MessageSendView,
    MessageActionView,
    DraftListView,
    DraftSaveView,
    DraftDeleteView,
    StudentProfileView,
)

urlpatterns = [
    path("health/", HealthView.as_view()),
    path("auth/validate-student-record/", ValidateStudentRecordView.as_view()),
    path("auth/send-signup-otp/", SendSignupOtpView.as_view()),
    path("auth/verify-signup-otp/", VerifySignupOtpView.as_view()),
    path("programs/", ProgramListView.as_view()),
    path("academic-calendar/", AcademicCalendarView.as_view()),
    path("announcements/", AnnouncementListView.as_view()),
    path("assignments/", AssignmentListView.as_view()),
    path("quizzes/", QuizListView.as_view()),
    path("quizzes/<int:quiz_id>/", QuizDetailView.as_view()),
    path("quizzes/submit/", QuizSubmitView.as_view()),
    path("students/<str:student_id>/results/", StudentResultsView.as_view()),
    path("students/<str:student_id>/results/exams/", StudentExamResultsView.as_view()),
    path("students/<str:student_id>/results/quizzes/", StudentQuizResultsView.as_view()),
    path("students/<str:student_id>/profile/", StudentProfileView.as_view()),
    path("messages/<str:user_id>/", MessageListView.as_view()),
    path("messages/<int:message_id>/detail/", MessageDetailView.as_view()),
    path("messages/send/", MessageSendView.as_view()),
    path("messages/<int:message_id>/action/", MessageActionView.as_view()),
    path("drafts/<str:user_id>/", DraftListView.as_view()),
    path("drafts/save/", DraftSaveView.as_view()),
    path("drafts/<int:draft_id>/delete/", DraftDeleteView.as_view()),
]
